### ISSUE TITLE
Improperly handles invalid sensor POST requests

### ISSUE THREAD

**Issue by wumbabum** [Jim-Hodapp-Coaching/ambi#6]
### Current behavior
- When receiving an invalid post request from either a mock client or physical sensor client, the Ambi backend accepts the request with incorrect response code (200):

```
[debug] Processing with AmbiWeb.ApiController.add_reading/2
  Parameters: %{}
  Pipelines: [:api]
[debug] Added new reading to the DB
[info] Sent 200 in 50ms
[debug] Broadcast details:
topic: "Ambi"
module: Ambi
event: :reading_refresh
```

### Expected behavior
- Expected Ambi backend responds to invalid request with 4xx error response code and not claim to have successfully added a sensor reading to the DB when it actually did not.

### To reproduce

1. Run ambi backend
2. Send an invalid POST request to ambi (possibly by using the [ambi mock client](https://github.com/Jim-Hodapp-Coaching/ambi_mock_client/commit/1735eabcdb520784de2a3d245be9b669569b4848))
3. Observe ambi responding with a 200 response to the POST request.

**Comment by jhodapp** [comment]
Closed by #13
